export default {
	"Domů": "Home",
	"Detail": "Detail",
	"Uživatelská sekce": "User section",
	"Odhlásit": "Logout",
	"Přihlásit": "Login",
	"Jazyky": "Languages",
	"Čeština": "Čeština",
	"English": "English",
	"Stránka s detailem": "Page with detail",
	"Popis hlavní stránky": "Main page description",
	"Uživatel {email}": "User {email}",
	"Přihlášení": "Login",
	"Nemáte login?": "Don't you have a login?",
	"Registrujte se": "Register",
	"email": "email",
	"heslo": "password",
	"Hlavní stránka": "Main page",
	"Bylo tam {count} {item} XXX{sdsdsd}YYYY": "There was {count} {item} XXX{sdsdsd}YYYY",
	"položka/položky/položek": "item/items/items",
	"Email není ve správném formátu!": "Email is not in correct format!",
	"Email je povinný!": "Email is required!",
	"Heslo je povinné!": "Password is required!",
	"Registrace": "Register",
	"Email": "Email",
	"Heslo": "Password",
	"Vytvořit účet": "Create account",
	"Uživatelská sekce pro {email}": "User section for {email}",
	"Neautorizovaný přístup!": "Unauthorized access!",
};
